### ISSUE TITLE
@reach/tabs 0.11.0 fails to build in Typescript

### ISSUE THREAD

**Issue by brandones** [reach/reach-ui#661]
### Current Behavior

```
[typescript] node_modules/@reach/tabs/dist/index.d.ts(34,35): error TS2307: Cannot find module '../../utils/src' or its corresponding type declarations.
[typescript] node_modules/@reach/tabs/dist/index.d.ts(96,31): error TS2307: Cannot find module '../../utils/src' or its corresponding type declarations.
[typescript] node_modules/@reach/tabs/dist/index.d.ts(118,34): error TS2307: Cannot find module '../../utils/src' or its corresponding type declarations.
[typescript] node_modules/@reach/tabs/dist/index.d.ts(140,33): error TS2307: Cannot find module '../../utils/src' or its corresponding type declarations.
[typescript] node_modules/@reach/tabs/dist/index.d.ts(153,39): error TS2307: Cannot find module '../../utils/src' or its corresponding type declarations.
```

However, it works in 0.10.0. I'm pinning to that version until this is resolved.

### Expected behavior

Typescript shouldn't fail.

### Reproducible example

Install `@reach/tabs`. My `tsconfig.json` is as follows:

```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "esnext",
    "allowSyntheticDefaultImports": true,
    "jsx": "react",
    "strictNullChecks": true,
    "moduleResolution": "node",
    "declaration": true,
    "declarationDir": "dist",
    "emitDeclarationOnly": true,
    "lib": [
      "dom",
      "es5",
      "scripthost",
      "es2015",
      "es2015.promise",
      "es2016.array.include",
      "es2018"
    ]
  },
  "include": ["src/**/*"]
```

### Suggested solution(s)

Seems like the declaration file `index.d.ts` has been written incorrectly.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    | @reach/tabs        |   0.11.0 |
| React            |         |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             |       | 12.16.1        |
| npm/yarn         |         |   6.14.1    |
| Operating System |         |   Ubuntu 20.04  |
| Typescript |  | 4.0.2 |

**Comment by ghostd** [comment]
Hi

Maybe a duplicate of #660

**Comment by brandones** [comment]
Looks like it, yes

**Comment by karlhorky** [comment]
Maybe also caused by the `ts-node --transpile-only` added in https://github.com/reach/reach-ui/pull/654 ...?

cc @chancestrickland

**Comment by chancestrickland** [comment]
Good catch, I'll close this in favor of #660 and investigate later today!
